//GET
export const GET_TODO = "GET_TODO";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAIL = "GET_TODO_FAIL";

//POST
export const POST_TODO = "POST_TODO";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODO_FAIL = "POST_TODO_FAIL";

//DELETE
export const DEL_TODO = "DEL_TODO";
export const DEL_TODO_SUCCESS = "DEL_TODO_SUCCESS";
export const DEL_TODO_FAIL = "DEL_TODO_FAIL";

//EDIT
export const EDIT_TODO = "EDIT_TODO";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAIL = "EDIT_TODO_FAIL";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
export const COMPLETE_TODO_FAIL = "COMPLETE_TODO_FAIL";
